### ISSUE TITLE
Increment version on release

### ISSUE THREAD

**Issue by mikaeleythor** [Akongstad/DevOps-group-p#116]
something like [this](https://github.com/marketplace/actions/automated-version-bump) in github workflow

```
- name:  'Automated Version Bump'
  uses:  'phips28/gh-action-bump-version@master'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag-prefix:  'v'
```
